#%RAML 1.0
title: Knowledge base API
version: v1
types:
  DocumentVersion:
    type: object
    description: Resource defining version of the document
    properties:
      hash: string
      created:
         type: int64
      updated:
         type: int64
  DocumentVersionList:
    type: object
    description: Resource defining list of document versions
    properties:
      items:
        type: array
        items: DocumentVersion
      items_total: integer
  ErrorDescription:
    description: Resource providing error description
    type: object
    properties:
      error_description: string
  Document:
    type: object
    description: Resource defining the document content
    properties:
      document_id: string
      document_url: string
      version: DocumentVersion
      etag: string
      elements:
        type: array
        items: DocumentElement
  DocumentElement:
    type: object
    description: Resource defining the content of the document's element
    properties:
      type: string
      text: string
  DocumentsList:
    type: object
    description: Resource defining all documents stored in the knowledge base sorted alphabetically
    properties:
      items:
        type: array
        items: string
/documents:
  get:
    description: Get all documents stored in the knowledge base
    responses:
      200:
        body:
          application/json:
            type: DocumentsList
      422:
        body:
          application/json:
            type: ErrorDescription
/document:
  post:
    body:
      application/json:
        type: Document
      responses:
        201:
          body:
            application/json:
              type: Document
        422:
          body:
            application/json:
          type: ErrorDescription
  /{documentID}:
    get:
      description: Get specific document
      responses:
        200:
          body:
            application/json:
              type: DocumentVersionList
        422:
          body:
            type: ErrorDescription
        404:
          description: The document that was requested was not found
    delete:
      description: Delete document with documentID from the knowledge base
      responses:
        204:
          description: Resource deleted
        422:
          body:
            type: ErrorDescription
        404:
          description: The document that was requested to delete was not found
    post:
      description: Create specific version of the document from the knowledge base
      responses:
        201:
          description: Resource created
        422:
          description: wrong paramters
          body:
            type: ErrorDescription
        404:
          description: The document that was requested to update was not found

    /{versionHash}:
      get:
        description: Get specific version of the document
        responses:
          200:
            body:
              application/json:
                type: Document
          422:
            body:
              type: ErrorDescription
          404:
            description: The document that was requested was not found
      delete:
        description: Delete specific version of the document from the knowledge base
        responses:
          204:
            description: Resource deleted
          422:
            body:
              type: ErrorDescription
          404:
            description: The document that was requested to delete was not found
      put:
        description: Update specific version of the document from the knowledge base
        responses:
          200:
            description: Resource updated
          422:
            description: wrong paramters
            body:
              type: ErrorDescription
          404:
            description: The document that was requested to update was not found
